### PR TITLE
fix warning from predict.lm

### PR DESCRIPTION
**Pull request by nhejazi**
The previous PR implemented a change in the test for futures -- specifically, it changed the seed for RNG to be more complex (away from `set.seed(1)`). Apparently, this causes a change in how folds are generated by origami's core functions, which in turn triggers a warning in `predict.lm`: "prediction from a rank-deficient fit may be misleading".

Here, we simply change the seed back (i.e., back to `set.seed(1)`), which stops this warning from arising.

This also includes some minor changes -- e.g., a change of the title of the JOSS paper...

### CODE REVIEW

**Comment by nhejazi** [comment]
Not sure why the appveyor build completes here, but then fails after merging the PR (maybe I'm missing something...)

**Comment by jeremyrcoyle** [comment]
It's failing on 

> Failure: MC is faster than sequential ---------------------------------------
  time_mc["elapsed"] is not strictly less than time_seq["elapsed"]. Difference: 0.09
  
Suggesting that it is building on something with more than one core. Anyways, the difference is pretty small (90ms) so it's possible the overhead of multicore is overwhelming the benefit of parallelizing in this case. Maybe we just fix this for now by changing the test to something like "MC is not substantially slower than sequential" and making it something like `expect_lte(time_mc,1.1*time_seq)`

**Comment by nhejazi** [comment]
That sounds fine to me. I had been thinking that it might be some shortcoming of Henrik's `future` package -- it seems like MC is not supported on Windows, which is what Appveyor builds on.

screen shot 2017-06-14 at 12 25 31 pm

**Comment by jeremyrcoyle** [comment]
Good catch. I forgot multicore doesn't work on windows. I'll make it skip that test on windows platforms.

**Pull request merged**
