### PR TITLE
Some changes to rolling and recursive CV

### PR DESCRIPTION
**Pull request by podTockom**
I added few more parameters to the two CVs... for selfish reasons. It should allow for a gap between training and validation now, as well as adding more points per iteration.

### CODE REVIEW

**Comment by ck37** [comment]
It would be good to add a test or two to this.

**Comment by nhejazi** [comment]
Thanks very much for the PR, the changes you made generally look good! Just two quick things:

1. As was pointed out, it's good to include a short unit test with your PR. If you will be doing this, you might want to use the time series example from the package vignette ([here](http://nimahejazi.org/origami/articles/generalizedCV.html), last example) to guide your test. It's also important to make sure that the vignette example is unchanged under the default values of the new arguments you've added.

2. It looks like the Travis CI build failed because the changes you made to the function are not reflected in the documentation. I think this would be fixed by a quick `devtools::document()`. (_side note:_ it's also good to make sure there are no errors in building the updated package locally, via `devtools::check` prior to pushing/PR).

Hope none of these recommendations were too repetitive. Thanks again for your PR!

**Comment by podTockom** [comment]
Awesome! Thanks for looking at it guys, I think there are few things we can do to make it pretty useful to time-series crowd. I am not as familiar with Travis CI, so I'll look into it. I tested it independently on the example in the vignette, and the default settings do not change the results.

**Comment by ck37** [comment]
This is a good page for info on testing if you haven't seen it yet: http://r-pkgs.had.co.nz/tests.html

**Pull request merged**
